### ISSUE TITLE
Justifying Aready Met Learning Objectives

### ISSUE THREAD

**Issue by maddoschwartz** [150PLD-Fall2019/Exemplars#13]
Hi! Would you like us to continue to justify a learning objective we already have received credit for?

**Comment by jmusca** [comment]
I don't believe that we should, but I do think that we might be able to argue that our work shows that we met another level of detail (at least that's what I'm going to try to do, wish me luck!)

**Comment by mpahrens** [comment]
@maddoschwartz It is not necessary for any grading purposes, but it also does not disrupt anything, so it is purely if you find use out of it at that point. I understand that any new system will have its quirks, so I appreciate everyone going along with my experiment, and I am very happy with the results folks have been showing so far.

@jmusca That is a good idea, but please don't be disheartened or discouraged if they are not awarded. As I designed the homework with the recommended level of detail in mind, students kind of have to work against my scaffolding in order to achieve above and beyond. For example, if I don't include any user stories or narratives in a homework, and it is all fill in the blank style coding examples with check expects (targeted towards Recall), the student will have to invent their own framing to show Recognition since I don't believe it exists in the homework as I designed it.
