### ISSUE TITLE
What is meant by "runtime system"?

### ISSUE THREAD

**Issue by dgrotenstein** [150PLD-Fall2019/Exemplars#21]
The comprehension questions ask if Slideshow has a runtime system. I am not particularly sure what is meant by this, and if it differs from the environment it can be programmed in (i.e. the DrScheme environment they discuss)? When I think runtime system in the context of Slideshow, I think there might be some system in place when a user is actually presenting the Slideshow presentation they made, in which case I don't think they mention this in the paper. But maybe I am just getting stuck on the wording, so maybe someone can help clarify :)

**Comment by mpahrens** [comment]
Great question,
Your intuition is correct, where I am asking about software the language designers provide for "presentation time" e.g. when the user is presenting the slideshow they made with Slideshow.
Since I don't intend this to be a guessing game, look at what the authors provide in terms of "slide-presentation systems" and tell me if those claims match your understanding of what a runtime system would be.

In terms of jargon, the DrScheme environment would be more of _IDE support_. where IDE is integrated development environment.
