### ISSUE TITLE
Why doesn't head work on getArgs?

### ISSUE THREAD

**Issue by jaredchandler** [150PLD-Fall2019/Exemplars#25]
Why doesn't this work?

> main :: IO () 
> main =  do x <- getArgs
>            y <- head x
>            print x
> 

Do I need to do some magic to make head work in the io monad?

**Comment by jaredchandler** [comment]
Oh... we have to use <$> to let it travel under the surface of the ocean to the monadic depths. 

Is there a way to run stack repl with arguments? that would make some of this easier.

**Comment by mpahrens** [comment]
head is a pure function. Remember `<-` is syntactic sugar for monadic bind.
The code you actually want:
<pre><code>
main :: IO ()
main = do
  xs <- getArgs
  let arg = head xs
</code></pre>

Since you are trying to apply a pure function (head :: [a] -> a) to a monadic value, this is a perfect example of the Functor pattern:

<pre><code>
main :: IO ()
main = do
  x <- head <$> getArgs
</code></pre>

which desugars as:
<pre><code>
head <$> getArgs >>= (\x -> ....rest of computation....) 
</code></pre>

As for passing args in interactive repl mode, the best I can offer you is using the set compiler option for ghci:
<pre><code>
> stack repl --system-ghc
Main Lib> :set args foo bar
Main Lib> import System.Environment
Main Lib System.Environment> getArgs
["foo","bar"] 
</code></pre>

**Comment by jaredchandler** [comment]
Thank you Matt!
