### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by dgrotenstein** [150PLD-Fall2019/Exemplars#30]
I'm not completely sure what we are supposed to be doing for this assignment....  It seems like we are writing programs in Haskell that are in a specific domain? Are these supposed to fully use the libraries you need to run that program? In the exemplars there seems to be no real functionality / library use and just stubs ?  For example, a domain I am trying to work with will be making diagrams... Should the necessary libraries for diagrams be used? I am having trouble understanding what the code examples are doing... Ahhhhh plz help.

**Comment by merterden98** [comment]
From what I understood, we are writing programs in a specific domain but these programs need not compile. I think the purpose of this is to just prototype some dummy code to start thinking about whether or not to pursue your domain/is it logical to make a dsl. So in your instance it might be like doing some api gluing or some definition of a datatype that you use in some functions. Something like: 

```haskell
datatype Diagram a = Left a | Right a | Top a | Bottom a | Nothing

drawDiagram:: Diagram a -> Display ()
drawDiagram = undefined
```

**Comment by mpahrens** [comment]
@merterden98 Is correct. The purpose of the assignment is to describe how users would program in your domain "the hard way" in whatever the current state of the art looks. But, I do not want you to debug a bunch of library code on such a short deadline. So, your code need not run nor compile. 

Also, it would be too hard to standardize the workload if I required programs to work since domains vary wildly in complexity.

Let me know if you still have questions

**Comment by mpahrens** [comment]
It might help to look at how we will be using the prose you write in class tomorrow:
https://www.cs.tufts.edu/comp/150PLD/ic10.html
