### ISSUE TITLE
hw03 Different set of questions on website vs github

### ISSUE THREAD

**Issue by jmusca** [150PLD-Fall2019/Exemplars#9]
I was actually going to ask about a typo (Q10 in the github version) but when looking at the website questions, I noticed that the set of questions are different: specifically Q5 on website vs Q5 and Q6 on github.

website: https://www.cs.tufts.edu/comp/150PLD/hw03-1.html
github: https://github.com/150PLD-Fall2019/Exemplars/blob/master/hw03-1-template-haskell/questions.md

I have been answering the github questions, and assume that that's ok.

**Comment by mpahrens** [comment]
Thanks for spotting this:
It doesn't matter which questions you answer, but it was my mistake. I intended for the questions on the website to be the ones because I re-thought that those two questions on the github might be a little too time consuming. But, they are good questions none-the-less.

I also fixed what I believe to be the typo.
